services:

  # Serviço do PostgreSQL
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"