services:

  # Serviço do PostgreSQL
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres_cyber
      POSTGRES_DB: cyber_db
    ports:
      - "5432:5432"